name: Auto Sync from Upstream

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Git Config
        run: |
          git config --global user.name 'Nahom Bot'
          git config --global user.email 'nahom@example.com'

      - name: Add Upstream & Pull
        run: |
          git remote add upstream https://github.com/fredrikandreas/IDATG2204-Project.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Sync from upstream"
          git push origin main
